name: 'Continuous integration'
on: ['push', 'pull_request']
jobs:
  cs:
    runs-on: 'ubuntu-20.04'
    name: 'Coding style'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v2'

      - name: 'Setup PHP'
        uses: 'shivammathur/setup-php@v2'
        with:
          php-version: '7.2'
          coverage: 'none'
          extensions: 'json, mbstring, tokenizer'
          tools: 'composer-normalize:2.13.3, php-cs-fixer:2.18.3'

      - name: 'Check PHP code'
        run: |
          php-cs-fixer fix --diff --dry-run --allow-risky=yes --using-cache=false
      - name: 'Check composer.json'
        run: |
          composer-normalize --diff --dry-run --indent-size=4 --indent-style=space --no-update-lock
