name: 'Continuous integration'
on:
  push:
    branches:
      - master
  pull_request: ~

jobs:
  cs:
    runs-on: 'ubuntu-20.04'
    name: 'Coding style'
    timeout-minutes: 10
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v2'

      - name: 'Setup PHP'
        uses: 'shivammathur/setup-php@v2'
        with:
          php-version: '8.1'
          coverage: 'none'
          extensions: 'json, mbstring, tokenizer'
          tools: 'composer-normalize:2.13.3, php-cs-fixer:3.8.0'

      - name: 'Check PHP code'
        run: |
          php-cs-fixer fix --diff --dry-run --allow-risky=yes --using-cache=no

      - name: 'Check composer.json'
        run: |
          composer-normalize --diff --dry-run --indent-size=4 --indent-style=space --no-update-lock

  phpstan:
    runs-on: 'ubuntu-latest'
    name: 'PHPStan'
    timeout-minutes: 10
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v2'

      - name: 'Setup PHP'
        uses: 'shivammathur/setup-php@v2'
        with:
          php-version: '8.1'
          coverage: 'none'
          extensions: 'curl, json, mbstring, openssl, tokenizer'
          tools: 'composer:v2, phpstan:1.7.11'

      - name: 'Get composer cache directory'
        id: 'composer_cache'
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: 'Cache dependencies'
        uses: 'actions/cache@v2'
        with:
          path: '${{ steps.composer_cache.outputs.dir }}'
          key: '${{ runner.os }}-composer-${{ hashFiles(''**/composer.json'') }}'
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: 'Update dependencies'
        run: |
          composer update --prefer-dist --no-interaction --no-progress --ansi

      - name: 'Cache PHPStan results'
        uses: 'actions/cache@v2'
        with:
          path: '/tmp/phpstan'
          key: 'phpstan-${{ github.sha }}'
          restore-keys: |
            ${{ runner.os }}-phpstan-
        continue-on-error: true

      - name: 'Run PHPStan analysis'
        run: |
          phpstan analyse --no-progress --no-interaction --ansi

  phpunit:
    runs-on: 'ubuntu-latest'
    name: 'PHPUnit (PHP ${{ matrix.php }})'
    timeout-minutes: 10
    strategy:
      matrix:
        php:
          - '7.4'
          - '8.0'
          - '8.1'
      fail-fast: false
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v2'

      - name: 'Setup PHP'
        uses: 'shivammathur/setup-php@v2'
        with:
          php-version: '${{ matrix.php }}'
          coverage: 'none'
          extensions: 'curl, json, mbstring, openssl, tokenizer'
          tools: 'composer:v2'

      - name: 'Get composer cache directory'
        id: 'composer_cache'
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: 'Cache dependencies'
        uses: 'actions/cache@v2'
        with:
          path: '${{ steps.composer_cache.outputs.dir }}'
          key: '${{ runner.os }}-composer-php${{ matrix.php }}-${{ hashFiles(''**/composer.json'') }}'
          restore-keys: |
            ${{ runner.os }}-composer-php${{ matrix.php }}-
            ${{ runner.os }}-composer-

      - name: 'Update dependencies'
        run: |
          composer update --prefer-dist --no-interaction --no-progress --ansi

      - name: 'Run tests'
        run: |
          vendor/bin/phpunit
